name: Comment when opened
on:
  issues:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$THING"
          gh issue comment $ISSUE --body "Thank you for opening this issue! Your branch is "
          export
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          THING: ${{ github.event.issue }}
