name: Comment when opened
on:
  issues:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo  '${{ toJSON(github.event.issue) }}'
          BRANCH_NAME="$NUMBER-$(echo $TITLE | sed 's/ /-/g;s/[^a-zA-Z0-9\-]//g;s/--*/-/g')"
          git checkout -b "$BRANCH_NAME" origin/master
          git commit -m "Created branch for issue $TITLE" --allow-empty
          git push origin HEAD
          gh pr create --draft -H "$BRANCH_NAME" -t "$TITLE" -b "body"
          gh issue comment $ISSUE --body "Thank you for opening this issue! Your branch is [$BRANCH_NAME](https://github.com/Zebreus/toenhtashneota/tree/$BRANCH_NAME).    [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/Zebreus/toenhtashneota/tree/$BRANCH_NAME)"
          export
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          TITLE: ${{ github.event.issue.title }}
          NUMBER: ${{ github.event.issue.number }}
